language: node_js
node_js:
  - node

env:
  # setup for integration tests
  - SYMPHONY_HOST=foundation-dev.symphony.com
  - SYMPHONY_KM_HOST=foundation-dev-api.symphony.com
  - SYMPHONY_SESSIONAUTH_HOST=foundation-dev-api.symphony.com
  - SYMPHONY_AGENT_HOST=foundation-dev-api.symphony.com
  # turn off any internal logging in tests
  - HUBOT_SYMPHONY_LOG_LEVEL=alert

before_script:
  # ensure we only have declared dependencies
  - npm prune
  # fetch certificates for integration tests against foundation-dev pod
  - "curl -s https://raw.githubusercontent.com/symphonyoss/contrib-toolbox/master/scripts/download-files.sh | bash"

script:
  # execute tests with coverage instrumentation
  - npm run-script test-cov
  # execute integration tests against foundation-dev pod
  - npm run-script it

after_success:
  # publish coverage results to coveralls
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
  # deploy to npm if required
  - npm run semantic-release
