language: node_js
node_js:
  - node

before_script:
  # ensure we only have declared dependencies
  - npm prune
  # fetch certificates for integration tests against foundation-dev pod
  - "curl -s https://raw.githubusercontent.com/symphonyoss/contrib-toolbox/master/scripts/download-files.sh | bash"

script:
  # execute tests with coverage instrumentation
  - npm run-script test-cov
  # execute integration tests against foundation-dev pod
  - ./it/run-odp.sh

after_success:
  # publish coverage results to coveralls
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
  # deploy to npm if required
  - npm run semantic-release
